#!/usr/bin/env ruby

$currSpeaker = nil
$currTime = "00:00:01"
$currText = []

timeRegex = /^(\d+):(\d\d)$/
speakerRegex = /^:(.*)$/

def dump_entry()
  if $currText.length > 0
    if $currText.length == 1 &&
       $currText[0][0] == '[' &&
       $currText[0][-2] == ']'
      speaker = nil
    else
      speaker = $currSpeaker
    end
    puts "- time: \"#{$currTime}\""
    if speaker
      puts "  speaker: #{speaker}"
    end
    puts "  caption: |"
    $currText.each do |line|
      puts "    #{line}"
    end
    puts
  end
end

ARGF.read.lines.each do |line|
  t = line.match(timeRegex)
  if t
    $currTime = sprintf("00:%02d:%02d", t[1].to_i, t[2].to_i)
  else
    s = line.match(speakerRegex)
    if s
      $currSpeaker = s[1]
    else
      if line == "\n"
        dump_entry()
        $currText = []
      else
        $currText << line
      end
    end
  end
end
dump_entry()
